---
foreman_proxy_container_image: "quay.io/foreman/foreman-proxy"
foreman_proxy_container_tag: "nightly"

foreman_proxy_name: "{{ ansible_facts['fqdn'] }}"
foreman_proxy_https_port: 8443
foreman_proxy_url: "https://{{ foreman_proxy_name }}:{{ foreman_proxy_https_port }}"

# Settings
foreman_proxy_trusted_hosts:
  - "{{ foreman_proxy_name }}"

foreman_proxy_base_features:
  - logs
foreman_proxy_plugins: []
foreman_proxy_features: "{{ foreman_proxy_base_features + foreman_proxy_plugins }}"
foreman_proxy_available_features: "{{ [] | available_foreman_proxy_plugins }}"
foreman_proxy_disabled_features: "{{ foreman_proxy_available_features | difference(foreman_proxy_features) }}"

foreman_proxy_foreman_server_url: "https://{{ ansible_facts['fqdn'] }}"

# BMC settings
foreman_proxy_bmc_ipmi_implementation: ipmitool
foreman_proxy_bmc_redfish_verify_ssl: true

# DNS settings
foreman_proxy_dns_provider: nsupdate
foreman_proxy_dns_provider_name: "dns_{{ foreman_proxy_dns_provider }}"
foreman_proxy_dns_ttl: 86400
