---
- name: Setup quadlet demo machine
  hosts:
    - quadlet
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/certificates.yml"
    - "../../vars/images.yml"
    - "../../vars/tuning/{{ tuning }}.yml"
    - "../../vars/database.yml"
    - "../../vars/foreman.yml"
    - "../../vars/base.yaml"
  roles:
    - role: pre_install
    - role: checks
      vars:
        checks_databases: "{{ all_databases }}"
    - role: certificates
      when: "certificates_source in ['default', 'custom_server']"
    - role: certificate_checks
      vars:
        certificate_checks_certificate: "{{ server_certificate }}"
        certificate_checks_key: "{{ server_key }}"
        certificate_checks_ca: "{{ server_ca_certificate }}"
    - role: postgresql
      when:
        - database_mode == 'internal'
        - "'foreman' in enabled_features or 'katello' in enabled_features"
    - role: redis
      when: "'foreman' in enabled_features or 'katello' in enabled_features"
    - role: candlepin
      when: "'katello' in enabled_features"
    - httpd
    - role: pulp
      when: "'katello' in enabled_features"
    - role: foreman
      when: "'foreman' in enabled_features"
    - role: systemd_target
    - role: iop_core
      when:
        - "'iop' in enabled_features"
        - database_mode == 'internal'
    - role: foreman_proxy
      when:
        - "'foreman-proxy' in enabled_features"
    - role: hammer
      when:
        - "'hammer' in enabled_features"
    - post_install
